# Generated by Django 3.2.5 on 2021-07-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=20)),
                ('abreviatura_estado', models.CharField(max_length=2)),
            ],
        ),
    ]
