# Generated by Django 3.2.5 on 2021-07-09 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=40)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrenos.estado')),
            ],
        ),
    ]
